mongodb:
  db_host: 127.0.0.1
  db_port: 27017
  connection_string: "mongodb+srv://.........."
  use_conn_str: false

sehuatang:
  # 域名
  domain_name: www.sehuatang.org
  # 板块id
  fid:
    - 103 # 高清中文字幕
    - 104 # 素人有码系列
    - 37 # 亚洲有码原创
    - 36 # 亚洲无码原创
    - 39 # 动漫原创
    - 160 # VR

  # 抓取页数，10代表1-10页，如抓取月份，建议数量写大一些
  page_num: 752
  # 抓取日期(格式: yyyy-mm-dd), 如果为空, 则抓取当前日期，支持正则匹配，可输入 yyyy-mm 抓取指定月份的所有日期
  date: 2022-03-31

proxy:
  # 代理服务器
  proxy_host: http://127.0.0.1:11223
  # 是否使用代理
  proxy_enable: false

# 推送配置，详情可参考企业微信开发者文档
sendMessage:
  # 是否发送消息
  send_wecom_enable: false
  # 企业ID
  corp_id: wwe1**********fa
  # 应用的凭证密钥
  corp_secret: Q5A************************n0
  # 应用ID
  agent_id: 10****2
  # mpnews消息类型页面图片media_id，需要提前将图片上传到企业微信素材库，接口返回media_id，不填则默认发文本消息
  media_id: 2******************************im
  # 接收的用户，多个用户用|分隔(如: use1|user2|user3)
  to_user: "@all"
  # telegram 推送
  send_telegram_enable: true
  tg_bot_token: 5307***************************o2Zw
  tg_chat_id: -7*********6
